spring:
  profiles:    active: local
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/Revature-RPM/configuration-repo
    
server:
  port: 8888

---
spring:
  profiles: local
  cloud:    config:      server:        git:
          default-label: local-deploy          uri: https://github.com/Revature-RPM/configuration-repo