spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: profile-config-migration
          uri: https://github.com/1810-oct08-java-usf/configuration-repo
    
server:
  port: 8888

#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka